In [ ]:
import numpy as np

In [ ]:
arr = np.array(5)  # 创建0维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)   # 数组的维度number of dimensions

In [ ]:
arr = np.array([1, 2, 3])  # 创建1维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)   # 数组的维度number of dimensions

In [ ]:
arr = np.array([ [1, 2, 3], [4, 5, 6]])  # 创建2维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)   # 数组的维度number of dimensions

### 同质性

In [ ]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

In [ ]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

## 2.ndarray的属性

In [ ]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置', arr.T)

In [ ]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置', arr.T)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的转置', arr.T)

## 3.ndarray的创建

In [ ]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1,dtype=np.float64)
print(arr.ndim)  # 属性
print(arr)

In [ ]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

In [ ]:
# 预定义形状
# 全0  全1  未初始化  固定值
# 全0
arr = np.zeros((2,3),dtype=int)
print(arr)
print(arr.dtype)

In [ ]:
arr = np.zeros((200,),dtype=int)
print(arr)

In [ ]:
# 全1
arr = np.ones((5,8),dtype=int)
print(arr)

In [ ]:
# 未初始化
arr = np.empty((2,3))
print(arr)

In [ ]:
arr = np.empty((4, 2))
print(arr)

In [ ]:
arr = np.full((3,4),2025)
print(arr)

In [ ]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

In [ ]:
#等差数列2 4 6 8 10
arr = np.arange(2,11,2)
print(arr)

In [ ]:
#等间隔数列
arr = np.linspace(0,100,5)
print(arr)

In [ ]:
#对数间隔数列
arr = np.logspace(0,100,4,base = 10)
print(arr)

arr2 = np.logspace(0,4,3,base = 2)
print(arr2)

## 4特殊矩阵的创建

In [ ]:
#单位矩阵:主对角线上数字为1,其他数字为0
arr = np.eye(3,4,dtype = int)
print(arr)

In [ ]:
#对角矩阵
arr2 = np.diag([5,1,2,3])
print(arr2)

In [ ]:
#随机数组的生成
#0~1范围内的浮点数
arr3 = np.random.rand(2,3)
print(arr3)
print("\n")
arr4 = np.random.uniform(3,6,(2,3))
print(arr4)

In [ ]:
#生成指定范围内的随机整数
arr5 = np.random.randint(3,30,(3,4))
print(arr5)

In [ ]:
#生成随机数列(正态分布)
#两边小,中间大
arr6 = np.random.randn(5,4 )
print(arr6)

In [ ]:
np.random.seed(200)
arr7 = np.random.randint(1,10,(2,5))
print(arr7)

## 5. ndarray的数据类型

In [ ]:
#bool 类型
arr8 = np.array([1,0,1,0],dtype = 'bool')
print(arr8)

## 6索引与切片

In [ ]:
#一维数组的索引与切片
arr9 = np.random.randint(1,100,20)
print(arr9)

In [ ]:
print(arr9[3])#索引
print(arr9[:])#全部
print(arr9[2:19])#范围
print(arr9[arr9>30])#bool大小
print(arr9[(arr9>30)&(arr9<70)])

In [ ]:
print(arr9[slice(2,19,3)])

In [ ]:
#二维数组
arr = np.random.randint(1,100,(3,5))
print(arr)

In [ ]:
print(arr[1,1])#索引
print("\n")
print(arr[:,:])
print("\n")
print(arr[0,:])
print("\n")
print(arr[arr>20])

## 7.ndarray的运算

In [ ]:
a = np.array([3,23,11])
b = np.array([1,7,9])
print(a+b)
print(a - b)
print(a*b)
print(a/b)
print(a%b)

In [ ]:
c=np.zeros(3)
for i in range(len(a)):
    c[i] = a[i]+b[i]
print(c)    
print(c**2)

In [ ]:
#二维数组运算
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

In [ ]:
c = np.zeros((3,3),dtype = int)
print(a+b)
print(a - b)
print(a*b)
print(a/b)
 

In [ ]:
#广播机制
a = np.array([1,2,3])#1*3
b = np.array([[4],[5],[6]])#3*1
print(a + b)

In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b) 

In [ ]:
#矩阵乘法运算 np.dot或者a@b
print(np.dot(a,b))
print(a@b)

In [ ]:
#矩阵的转置
print(np.transpose(a))
print(a.T)

In [ ]:
#矩阵的求逆
print(np.linalg.inv(a))
print(a@np.linalg.inv(a))

## 8.numpy的基本数学函数

In [95]:
##计算平方根
print(np.sqrt(9))
print(np.sqrt([4,9,16]))

arr = np.array([9,16,25])
print(np.sqrt(arr))

3.0
[2. 3. 4.]
[3. 4. 5.]


In [101]:
#计算指数 e^X = y
print(np.exp(1))

2.718281828459045


In [103]:
#计算自然对数 ln y = x
print(np.log())

0.9969486348916096


In [117]:
#计算正弦值 余弦值
print(np.sin(0))
print(np.cos(np.pi))

0.0
-1.0


In [118]:
#计算绝对值
arr = np.array([-1,-2,-3])
print(np.abs(arr))

[1 2 3]
